name: Publish Reporting Packages

on:
  push:
    branches:
      - main
    paths:
      - 'src/liftoff-reporting/**'
      - 'src/tapjoy-reporting/**'
      - 'src/appsamurai-reporting/**'
      - 'src/singular-reporting/**'
      - 'src/kayzen-reporting/**'
      - 'src/jampp-reporting/**'
      - 'src/applovin-reporting/**'
      - 'src/feedmob-reporting/**'
      - 'src/ironsource-reporting/**'
      - 'src/mintegral-reporting/**'
      - 'src/inmobi-reporting/**'
      - 'src/ironsource-aura-reporting/**'
      - 'src/smadex-reporting/**'
      - 'src/samsung-reporting/**'
      - 'src/rtb-house-reporting/**'
      - 'src/femini-reporting/**'
      - 'src/sensor-tower/**'
      - 'src/work-journals/**'

  workflow_dispatch:
    inputs:
      package:
        description: 'Reporting package to publish (leave empty to detect from changed files)'
        required: false
        type: choice
        options:
          - ''
          - liftoff
          - tapjoy
          - appsamurai
          - singular
          - kayzen
          - jampp
          - applovin
          - feedmob
          - ironsource
          - mintegral
          - inmobi
          - ironsource-aura
          - smadex
          - samsung
          - rtb-house
          - femini
          - work-journals
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - id: set-matrix
        name: Detect changed packages
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.package }}" != "" ]]; then
            # Use manually specified package
            echo "matrix={\"package\":[\"${{ github.event.inputs.package }}\"]}" >> $GITHUB_OUTPUT
          else
            # Detect from changed files
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)

            # Initialize an empty JSON array
            JSON_ARRAY="[]"

            # Add packages to JSON array if they have changes
            if echo "$CHANGED_FILES" | grep -q "src/liftoff-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["liftoff"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/tapjoy-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["tapjoy"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/appsamurai-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["appsamurai"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/singular-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["singular"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/kayzen-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["kayzen"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/jampp-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["jampp"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/applovin-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["applovin"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/feedmob-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["feedmob"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/ironsource-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["ironsource"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/mintegral-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["mintegral"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/inmobi-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["inmobi"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/ironsource-aura-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["ironsource-aura"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/smadex-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["smadex"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/samsung-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["samsung"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/rtb-house-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["rtb-house"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/femini-reporting/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["femini"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/sensor-tower/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["sensor-tower"]')
            fi
            if echo "$CHANGED_FILES" | grep -q "src/work-journals/"; then
              JSON_ARRAY=$(echo $JSON_ARRAY | jq -c '. += ["work-journals"]')
            fi
            # Generate the matrix output with proper JSON formatting
            echo "matrix={\"package\":$JSON_ARRAY}" >> $GITHUB_OUTPUT
          fi

  publish:
    needs: detect-changes
    if: ${{ fromJSON(needs.detect-changes.outputs.matrix).package[0] != null }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.detect-changes.outputs.matrix) }}
    defaults:
      run:
        working-directory: src/${{ matrix.package }}-reporting

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
